import type { Metadata } from "next";
import {Providers} from "./providers";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='dark'>
      <body className='text-white'>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
